const data = {
  products: [
    {
      _id: "1",
      title: "Preppy Fleece Sweater",
      image: "plaid-fleece.jpg",
      description:
        "This is for all the latest trends, no matter who you are, where you’re from and what you’re up to. Preppy is always in. Created by us, styled by you. Ya nerd.",
      price: "20",
      sizes: ["S", "L"],
      countInStock: 15,
      rating: 4.5,
      numReviews: 15,
      featured: true,
    },
    {
      _id: "2",
      title: "The Grinch Vest",
      image: "grinch-fur.jpg",
      description:
        "Limited edition mossy green shiny faux fur for the Grinchiest Grinch of all the Grinches. Christmas is coming!",
      price: "75",
      sizes: ["S", "M", "L"],
      countInStock: 0,
      rating: 4.5,
      numReviews: 23,
      featured: false,
    },
    {
      _id: "3",
      title: "Bad Ass Hoodie",
      image: "badass-hoodie.jpg",
      description:
        "Black Bad Ass Hoodie. Cotton 95% / spandex 5%. Light and stretchy for those chilly nights!",
      price: "19",
      sizes: ["S", "M", "L", "XL"],
      countInStock: 20,
      rating: 4.1,
      numReviews: 71,
      featured: false,
    },
    {
      _id: "4",
      title: "Blue Knit Sweater",
      image: "blue-knit.jpg",
      description:
        "This sweater is perfect for the lively tuna fish-lovers in your home, equipped with a stretchy waist to support their activities. It comes with a smile on your face and a securely sewn-in button in the neck to describe your kitty's deepest desires.",
      price: "35",
      sizes: ["XS", "S", "M", "L"],
      countInStock: 30,
      rating: 4.7,
      numReviews: 55,
      featured: false,
    },
    {
      _id: "5",
      title: "Dark Lord Winter Coat",
      image: "winter-sweater.jpg",
      description:
        "You'll barely feel the frost when you're wearing the Dark Lord's winter coat. Designed with a high neck and fur lined hood to really lock in heat, it's a must come cold days. Roll on winter.",
      price: "80",
      sizes: ["M", "L"],
      countInStock: 4,
      rating: 4.1,
      numReviews: 54,
      featured: false,
    },
    {
      _id: "6",
      title: "The Wolf Vest",
      image: "fur.jpg",
      description:
        "The Grey Wolf has a true lust for life and feels fulfilled when conquering challenges. This Spirit often has much to teach those around them and naturally assumes the role of a silent leader. A Grey Wolf will always fight for what is right. 10% of net profits donated to help endangered species.",
      price: "50",
      sizes: ["S", "M"],
      countInStock: 7,
      rating: 4.8,
      numReviews: 64,
      featured: true,
    },
    {
      _id: "7",
      title: "Minimalist Mohair Sweater",
      image: "tan-sweater.jpg",
      description:
        "This beautiful and comfortable sweater is hand knitted. It is hand/machine washable (mohair function, 30 degrees C/ 86 F). Yarn is 75% mohair and 25% polyamide.",
      price: "35",
      sizes: ["XS", "M", "L"],
      countInStock: 12,
      rating: 4.5,
      numReviews: 30,
      featured: false,
    },
    {
      _id: "8",
      title: "Tuxedo Knight Sweater",
      image: "tuxedo-sweater.jpg",
      description:
        "Custom hand tailored tuxedo, perfect for those special occassions. A truly classic piece that can be worn for years to come.",
      price: "30",
      sizes: ["M"],
      countInStock: 23,
      rating: 3.5,
      numReviews: 34,
      featured: false,
    },
    {
      _id: "9",
      title: "No, Nope, Never Fleece",
      image: "nope-fleece.jpg",
      description:
        "This piece is sure to keep you layered up and looking good throughout the weather event that is everyday life and also for days you just dont wanna.",
      price: "25",
      sizes: ["S", "M", "XL"],
      countInStock: 19,
      rating: 4.3,
      numReviews: 47,
      featured: false,
    },
    {
      _id: "10",
      title: "Turtle Style Sweater",
      image: "turtleneck.jpg",
      description:
        "TMNT inspired ribbed sweater featuring a ribbed rolled neck, a relaxed fit and fine knit.",
      price: "35",
      sizes: ["M", "L", "XL"],
      countInStock: 11,
      rating: 4.1,
      numReviews: 34,
      featured: false,
    },
    {
      _id: "11",
      title: "Rwar Shirt",
      image: "dino-shirt.jpg",
      description:
        "This one's for all the dinosaur lovers out there!. Gain instant leopard dino vibes while stomping around and staying warm. ",
      price: "40",
      sizes: ["L"],
      countInStock: 10,
      rating: 4.0,
      numReviews: 87,
      featured: false,
    },
    {
      _id: "12",
      title: "Black Panther",
      image: "blackfur-vest.jpg",
      description:
        "Soft and sleek pullover vest made with 100% real panther fur for those extra chilly days. Made in honor of Chadwich 'T'Challa' Boseman. Wakanda Furever!",
      price: "50",
      sizes: ["S", "M", "L"],
      countInStock: 5,
      rating: 4.9,
      numReviews: 120,
      featured: true,
    },
  ],
};

export default data;
